### ISSUE TITLE
Slices of 1..1 elements create contradictory profiles

### ISSUE THREAD

**Issue by richardtownleyoneill-ADHA** [hl7au/au-fhir-base-stu3#5]
Where a 1..1 polymorphic element is sliced by type, unless the slices are explicitly given a min cardinality of 0, they get a min cardinality of 1. Which makes a profile that is impossible to conform to. See Zulip thread [Slicing mandatory elements](https://chat.fhir.org/#narrow/stream/179177-conformance/topic/Slicing.20mandatory.20elements)

Explicitly set the min cardinality of slices to 0 in affected profiles.
This includes
Medication.ingredient.item[x]
MedicationRequest.medication[x]
MedicationDispense.medication[x]
MedicationStatement.medication[x]
MedicationAdministration.medication[x]

**Comment by richardtownleyoneill-ADHA** [comment]
Hi Brett.
I'd like to make the changes to Medication.ingredient.item[x] and MedicationStatement.medication[x] and submit a pull request for them. Having those changes in au-fhir-base-stu3 is urgent for the CI team.

**Comment by dbojicic-agency** [comment]
Richard, please see issue https://github.com/hl7au/au-fhir-base-stu3/issues/6 re Medication.ingredient.item[x] slice; the AMT slice might get removed.

**Comment by brettesler-ext** [comment]
good thanks Richard

**Comment by vikasmittal-dh** [comment]
The following changes has been completed via this pull request https://github.com/hl7au/au-fhir-base-stu3/pull/8 

- For **MedicationStatement.medication[x]** the cardinality of **medicationCodableConcept** and **medicationReference** has been relaxed from 1..1 to 0..1
- For **Medication.ingredient.item[x]** the cardinality of **itemCodableConcept** has been relaxed from 1..1 to 0..1. 
- Additionally for **Medication.ingredient.item[x]**, the slice for **itemReference** was not present in the profile and thus the profile was not allowing the reference to exist in an instance. Hence the profile has also been modified by adding a slice for **itemReference** with the cardinality of 0..1. The references allowed under this reference has been updated to **au-medication** and **au-substance** profiles instead of STU3 medication and substance resources.

**Comment by brettesler-ext** [comment]
Brett will fix MedicationStatement|Dispense|Administration

**Comment by brettesler-ext** [comment]
MedicationStatement is fixed

**Comment by brettesler-ext** [comment]
fixed 0d5620f
